"""Public authoritative-routing entrypoint and phase runner."""
from __future__ import annotations
from .Dependencies import *
from .Phases import AUTHORITATIVE_ROUTING_PHASES
from .RunState import AuthoritativeRoutingServices, AuthoritativeRoutingState


def RunAuthoritativeRoutingPhases(
    State: AuthoritativeRoutingState,
    Services: AuthoritativeRoutingServices,
    Phases: tuple[Callable[[AuthoritativeRoutingState, AuthoritativeRoutingServices], Any], ...] = AUTHORITATIVE_ROUTING_PHASES,
) -> Any:
    """Run the ordered phases with an explicitly supplied dependency table."""
    for RunPhase in Phases:
        Outcome = RunPhase(State, Services)
        if Outcome.Returned:
            return Outcome.Value
    raise RuntimeError('authoritative routing phases completed without a result')

def RouteAuthoritativeResources(Placed: Any, Resources: RoutingResources, SearchMarginX: int, SearchMarginZ: int, MaximumRoutingHeight: int, Policy: PhysicalDesignPolicy=DefaultPhysicalDesignPolicy, Technology: RedstoneRoutingTechnology=DefaultRedstoneRoutingTechnology, ProgressCallback: Callable[[int, int], None] | None=None, DiagnosticCallback: Callable[[RoutingIterationMetrics, str | None], None] | None=None, AdaptiveLayerFloor: int | None=None, SharedRoutingStarted: float | None=None, EscalationHistory: tuple[dict[str, object], ...]=(), ReservationVariant: int=0, LaneDiversityLevel: int=0, CandidateDiversityLevel: int=0, SkipStrictPortalReservation: bool=False, EscalationStates: tuple[tuple[object, ...], ...]=(), Deadline: RoutingDeadline | None=None, RetainedCandidateCache: dict[str, tuple[NetRouteCandidate, ...]] | None=None, RetainedCandidateMetadata: dict[str, dict[str, tuple[str, int, int, int]]] | None=None, PriorCandidateCache: dict[str, tuple[NetRouteCandidate, ...]] | None=None, PriorCandidateMetadata: dict[str, dict[str, tuple[str, int, int, int]]] | None=None, RegenerateSignals: frozenset[str]=frozenset(), RawPortalCache: RawPortalGeometryCache | None=None, PreparedPortalCache: PreparedPortalDomainCache | None=None, PreparePortalGeometryOnly: bool=False, PrepareTrackAssignmentOnly: bool=False, PrepareRawTrackAssignmentDomainOnly: bool=False, FrozenTrackAssignmentPreparation: TrackAssignmentPreparation | None=None, ValidateClusterInterfaceForeignAccessOnly: bool=False, ValidatePhysicalComponentForeignPortalSupportOnly: bool=False, PrepareClusterInterfaceAssignmentOnly: bool=False, PrepareComponentRoutingProblemOnly: bool=False, PreparePhysicalComponentAssemblyOnly: bool=False, PreparePhysicalComponentPortFactorDomainOnly: bool=False, DeferClusterBoundaryLeaseUntilCapacityPrecheck: bool=False, UnboundOwnedSignalFrontierProofCallback: Callable[[ComponentRoutingProblem], None] | None=None, RequireCompleteClusterInterfaceDomain: bool=False, ClusterInterfaceRealizabilityNogoods: tuple[ClusterInterfaceRealizabilityNogood, ...]=(), ClusterInterfaceStateFingerprint: str='', ClusterInterfaceLocalRouteFingerprint: str='', ForbiddenClusterInterfaceAssignmentFingerprints: frozenset[str]=frozenset(), ClusterInterfaceFrozenPatternFingerprints: dict[str, str] | None=None, ClusterInterfaceFrozenReservations: tuple[PortalReservation, ...]=(), LocalClaimReleaseHistory: frozenset[str]=frozenset(), AvoidRoutingPositions: frozenset[Position3]=frozenset(), AvoidRoutingPositionsBySignal: dict[str, frozenset[Position3]] | None=None, ClusterLeaseCandidateDomainOffsets: dict[str, int] | None=None, ClusterLeaseCandidateRealizabilityNogoods: tuple[ClusterLeaseCandidateRealizabilityNogood, ...]=(), PriorClusterLeaseSignalPatternFingerprints: dict[str, str] | None=None) -> RoutedDesign | PreparedPhysicalComponentPortFactorDomain:
    """Generate portals and select complete capacity-one routes in Rust."""
    State = AuthoritativeRoutingState(Placed=Placed, Resources=Resources, SearchMarginX=SearchMarginX, SearchMarginZ=SearchMarginZ, MaximumRoutingHeight=MaximumRoutingHeight, Policy=Policy, Technology=Technology, ProgressCallback=ProgressCallback, DiagnosticCallback=DiagnosticCallback, AdaptiveLayerFloor=AdaptiveLayerFloor, SharedRoutingStarted=SharedRoutingStarted, EscalationHistory=EscalationHistory, ReservationVariant=ReservationVariant, LaneDiversityLevel=LaneDiversityLevel, CandidateDiversityLevel=CandidateDiversityLevel, SkipStrictPortalReservation=SkipStrictPortalReservation, EscalationStates=EscalationStates, Deadline=Deadline, RetainedCandidateCache=RetainedCandidateCache, RetainedCandidateMetadata=RetainedCandidateMetadata, PriorCandidateCache=PriorCandidateCache, PriorCandidateMetadata=PriorCandidateMetadata, RegenerateSignals=RegenerateSignals, RawPortalCache=RawPortalCache, PreparedPortalCache=PreparedPortalCache, PreparePortalGeometryOnly=PreparePortalGeometryOnly, PrepareTrackAssignmentOnly=PrepareTrackAssignmentOnly, PrepareRawTrackAssignmentDomainOnly=PrepareRawTrackAssignmentDomainOnly, FrozenTrackAssignmentPreparation=FrozenTrackAssignmentPreparation, ValidateClusterInterfaceForeignAccessOnly=ValidateClusterInterfaceForeignAccessOnly, ValidatePhysicalComponentForeignPortalSupportOnly=ValidatePhysicalComponentForeignPortalSupportOnly, PrepareClusterInterfaceAssignmentOnly=PrepareClusterInterfaceAssignmentOnly, PrepareComponentRoutingProblemOnly=PrepareComponentRoutingProblemOnly, PreparePhysicalComponentAssemblyOnly=PreparePhysicalComponentAssemblyOnly, PreparePhysicalComponentPortFactorDomainOnly=PreparePhysicalComponentPortFactorDomainOnly, DeferClusterBoundaryLeaseUntilCapacityPrecheck=DeferClusterBoundaryLeaseUntilCapacityPrecheck, UnboundOwnedSignalFrontierProofCallback=UnboundOwnedSignalFrontierProofCallback, RequireCompleteClusterInterfaceDomain=RequireCompleteClusterInterfaceDomain, ClusterInterfaceRealizabilityNogoods=ClusterInterfaceRealizabilityNogoods, ClusterInterfaceStateFingerprint=ClusterInterfaceStateFingerprint, ClusterInterfaceLocalRouteFingerprint=ClusterInterfaceLocalRouteFingerprint, ForbiddenClusterInterfaceAssignmentFingerprints=ForbiddenClusterInterfaceAssignmentFingerprints, ClusterInterfaceFrozenPatternFingerprints=ClusterInterfaceFrozenPatternFingerprints, ClusterInterfaceFrozenReservations=ClusterInterfaceFrozenReservations, LocalClaimReleaseHistory=LocalClaimReleaseHistory, AvoidRoutingPositions=AvoidRoutingPositions, AvoidRoutingPositionsBySignal=AvoidRoutingPositionsBySignal, ClusterLeaseCandidateDomainOffsets=ClusterLeaseCandidateDomainOffsets, ClusterLeaseCandidateRealizabilityNogoods=ClusterLeaseCandidateRealizabilityNogoods, PriorClusterLeaseSignalPatternFingerprints=PriorClusterLeaseSignalPatternFingerprints)
    Services = AuthoritativeRoutingServices.FromNamespace(globals())
    return RunAuthoritativeRoutingPhases(State, Services)
